--- 

- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
      name: nginx
      state: started
  become: yes

- name: copy nginx config file
  copy:
    src: static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
  become: yes

- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes

  notify: restart nginx

- name: copy web pages
  copy:
    src: ~/Dropbox/VimWiki/export/html/
    dest: /usr/share/nginx/html/

