---
   - name: Create symbolic link 
     file:
       src: "repos/git/dotfiles/{{ item }}"
       path: "{{ item }}"
       state: link
       force: yes
     loop:
       - .vimrc
       - .bash_aliases
       - .bash_profile
       - .bashrc

